// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsStoreA.Models;

namespace SportsStoreA.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190613162135_Ordenes2")]
    partial class Ordenes2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportsStoreA.Models.LineaCarrito", b =>
                {
                    b.Property<long>("LineaCarritoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<long?>("OrdenId");

                    b.Property<long>("ProductoId");

                    b.HasKey("LineaCarritoId");

                    b.HasIndex("OrdenId");

                    b.ToTable("LineaCarrito");
                });

            modelBuilder.Entity("SportsStoreA.Models.Orden", b =>
                {
                    b.Property<long>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired();

                    b.Property<bool>("Embarcar");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<long>("PagoId");

                    b.HasKey("OrdenId");

                    b.HasIndex("PagoId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("SportsStoreA.Models.Pago", b =>
                {
                    b.Property<long>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoAuth")
                        .IsRequired();

                    b.Property<int>("CodigoSeguridad");

                    b.Property<string>("NumeroTarjeta")
                        .IsRequired();

                    b.Property<decimal>("Total");

                    b.Property<string>("VencimientoTarjeta")
                        .IsRequired();

                    b.HasKey("PagoId");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("SportsStoreA.Models.Producto", b =>
                {
                    b.Property<long>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.Property<decimal>("Precio");

                    b.Property<long?>("ProveedorId");

                    b.HasKey("ProductoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SportsStoreA.Models.Proveedor", b =>
                {
                    b.Property<long>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad");

                    b.Property<string>("Nombre");

                    b.Property<string>("Provincia");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SportsStoreA.Models.Rating", b =>
                {
                    b.Property<long>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ProductoId");

                    b.Property<int>("Stars");

                    b.HasKey("RatingID");

                    b.HasIndex("ProductoId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("SportsStoreA.Models.LineaCarrito", b =>
                {
                    b.HasOne("SportsStoreA.Models.Orden")
                        .WithMany("Productos")
                        .HasForeignKey("OrdenId");
                });

            modelBuilder.Entity("SportsStoreA.Models.Orden", b =>
                {
                    b.HasOne("SportsStoreA.Models.Pago", "pago")
                        .WithMany()
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SportsStoreA.Models.Producto", b =>
                {
                    b.HasOne("SportsStoreA.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SportsStoreA.Models.Rating", b =>
                {
                    b.HasOne("SportsStoreA.Models.Producto", "Producto")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
